const products = [
  {
    id: 0,
    name: "Dress shirt",
    price: 100,
    description: "Light blue",
    imgSrc: "img/products/dress/blue/blue-on-model.webp",
  },
  {
    id: 1,
    name: "Dress shirt",
    price: 100,
    description: "White",
    imgSrc: "img/products/dress/white/white-on-model.webp",
  },
  {
    id: 2,
    name: "Dress shirt",
    price: 100,
    description: "Green",
    imgSrc: "img/products/dress/green/green-on-model.webp",
  },
  {
    id: 3,
    name: "Dress shirt",
    price: 100,
    description: "Navy",
    imgSrc: "img/products/dress/navy/navy-on-model.webp",
  },
  {
    id: 4,
    name: "Oxford shirt",
    price: 100,
    description: "Light blue",
    imgSrc: "img/products/oxford/blue/blue-on-model.webp",
  },
  {
    id: 5,
    name: "Oxford shirt",
    price: 100,
    description: "White",
    imgSrc: "img/products/oxford/white/white-on-model.webp",
  },
  {
    id: 6,
    name: "Oxford shirt",
    price: 100,
    description: "Green",
    imgSrc: "img/products/oxford/green/green-on-model.webp",
  },
  {
    id: 7,
    name: "Oxford shirt",
    price: 100,
    description: "Navy",
    imgSrc: "img/products/oxford/navy/navy-on-model.webp",
  },
  {
    id: 8,
    name: "Cuban shirt",
    price: 100,
    description: "Light blue",
    imgSrc: "img/products/cuban/blue/blue-on-model.webp",
  },
  {
    id: 9,
    name: "Cuban shirt",
    price: 100,
    description: "White",
    imgSrc: "img/products/cuban/white/white-on-model.webp",
  },
  {
    id: 10,
    name: "Cuban shirt",
    price: 100,
    description: "Green",
    imgSrc: "img/products/cuban/green/green-on-model.webp",
  },
  {
    id: 11,
    name: "Cuban shirt",
    price: 100,
    description: "Navy",
    imgSrc: "img/products/cuban/navy/navy-on-model.webp",
  },
];
